version: '3'
services:
  ctf:
    build: pythonathon_ctf_server
    expose: 
     - 8000
  proxy:
    image: ployst/nginx-ssl-proxy
    environment:
     - ENABLE_SSL=true
     - ENABLE_BASIC_AUTH=false
     - TARGET_SERVICE=ctf
    volumes:
     - /etc/nginx/ssl/nginx.crt:/etc/secrets/proxycert
     - /etc/nginx/ssl/nginx.key:/etc/secrets/proxykey
     - /etc/nginx/ssl/dhparam.pem:/etc/secrets/dhparam
    ports:
     - "80:80"
     - "443:443"