version: '3'
services:
  ctf:
    build: pythonathon_ctf_server
    restart: always
    expose:
     - 8000
  proxy:
    image: danieldent/nginx-ssl-proxy
    restart: always
    environment:
      UPSTREAM: ctf:8000
      SERVERNAME: pythonathon.davidmaxson.name
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/etc/letsencrypt"